### PR TITLE
Python2 / Python3 Compatibility

### PR DESCRIPTION
**Pull request by FrancescoCasalegno**
While working on the Python2 / Python 3 compatibility of STEPS source code (HBP_STEPS), we also need to have Validation Tests that are py2 / py3 compatible in order to run all the tests in the correct way.

### CODE REVIEW

**Comment by WeiliangChenOIST** [comment]
@FrancescoCasalegno From the changes it seems old users also need to change their old simulation scripts as well, right? Any automatic way to do it?

**Comment by FrancescoCasalegno** [comment]
Hi @WeiliangChenOIST , I am not sure I understood your comment, in any case after the merge of this PR all the STEPS_Validation will be still compatible with a python2 build of HBP_STEPS. 

By automatic way you mean something different from `git pull origin master`?

**Comment by WeiliangChenOIST** [comment]
@FrancescoCasalegno  no no, I meant if a user wrote a simulation script in python 2.7, they also need to update their script for Python3, right?

**Comment by FrancescoCasalegno** [comment]
@WeiliangChenOIST well, this concerns more the updates on HBP_STEPS (future pr for py2/py3 coming soon) but in any cases changing their scripts is not needed as the code is compatible and tested on both python2 and python3.

The only case where they need to modify their own simulation scripts is if *they* want to personally switch to python3. Any other user who still likes python2 will be still supported.

**Pull request merged**
